# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: samymone <samymone@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/09/19 20:57:25 by samymone          #+#    #+#              #
#    Updated: 2019/09/19 20:57:25 by samymone         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

#    PROJECT    #
# NAME = checker #

NAME = push_swap

#    DIRECTORIES    #
SRC_DIR = ./src/
LIB_DIR = ./libft/
OBJ_DIR = ./obj/
SRC_INC_DIR = ./includes/
LIB_INC_DIR = ./libft/includes

#    FLAGS    #
CFLGS = -Wall -Werror -Wextra
CFLGS_DBG = -g -fsanitize=address
LFLGS = -L$(LIB_DIR) -lft
CC = gcc

#    LIBFT    #
LIBFT = $(LIB_DIR)/libft.a

#    SOURCES AND HEADERS    #
SRC_FILES = ft_checker.c ft_error.c ft_stack.c ft_validation.c px.c rrx.c rx.c \
	sx.c is_sorted.c ft_push_swap.c sorting_algorythm.c extra_functions.c
SRCS = $(addprefix $(SRC_DIR), $(SRC_FILES))
OBJS = $(patsubst $(SRC_DIR)/%.c,$(OBJ_DIR)/%.o, $(SRCS))
DEPS = $(OBJS:.o=.d)

#    INCLUDES    #
INCL = -I$(SRC_INC_DIR) -I$(LIB_INC_DIR)

#    RULES    #
.PHONY: all clean fclean re

all: $(NAME)

-include: $(DEPS)
$(OBJ_DIR)/%.o: $(SRC_DIR)/%.c | $(OBJ_DIR)
	$(CC) $(CFLGS) -c -o $@ $< $(INCL) -g

$(OBJ_DIR):
	mkdir -p $(OBJ_DIR)

$(LIBFT):
	$(MAKE) -C $(LIB_DIR)

$(NAME): $(OBJS) $(LIBFT)
	$(CC) $(CFLAGS) -o $(NAME) $(OBJS) $(INCL) $(LFLGS) -g

clean:
	rm -rf $(OBJ_DIR)
	$(MAKE) -C $(LIB_DIR) clean

fclean: clean
	rm -rf $(NAME)
	$(MAKE) -C $(LIB_DIR) fclean

re: fclean all

#    AUTO GENERATED BY 21 MAKEFILE GENERATOR (21MFG)    #
#         https://github.com/ltanailov/21mfg.git        #
